#1
#End of the lore sequence. The arena chunks were force-loaded back at lore/6, so they are already
#generated by now. Place the structures on separate ticks (tower now, mountain next tick) and only
#then teleport players in -- this spreads the heavy work out instead of doing generation + placement
#+ teleport all in one frozen tick like the original did.
function inqui:lore/finale_place_tower
schedule function inqui:lore/finale_place_mountain 10t
schedule function inqui:lore/17_enter 20t
